Algoritmo "semnome"
// 
Var
enq:inteiro
val:inteiro

Inicio

escreval("---------------------------------------------")
escreval("           CONTA QUASE INTELIGENTE           ")
escreval("---------------------------------------------")

escreval("Por favor adicione números em ordem crescente")
escreva(" \> Início ? ")
leia(enq)
escreva(" \> Fim ? ")
leia(val)
escreval("")
enquanto (enq <= val) faca
    escreva ( enq, ".. ")
    enq <- enq + 1
fimenquanto


Fimalgoritmo   

